name: demo test yaml

on: [push]

jobs:
  build:

    runs-on: runner_e
    permissions:
      repository-projects: write
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - run: |
          export PATH=/mnt/petrelfs/caifcicd/dev/git/git-2.9.3/bin:$PATH
          echo $GITHUB_WORKSPACE
          git clone https://github.com/kkscilife/debugtmp.git
      
      - uses: actions/checkout@v3
        with: 
          github-server-url: 'https://github.com/kkscilife/debugtmp'
      - run: |
          echo $PATH
          whereis git
          ls -a
          git --version
          git branch
      #- name: Set up Python ${{ matrix.python-version }}
        #uses: actions/setup-python@v4
        #with:
          #python-version: ${{ matrix.python-version }}
      - name: run demo python
        run: |
          source /mnt/petrelfs/qa-caif-cicd/env/ray1.13.0
          echo $USER
          python ./demo.py
          ls
          pwd
      - name: kk echo demo
        run: |
          # stop the build if there are Python syntax errors or undefined names
          sh ./tmp.sh
          pwd
      - name: tmp
        run: |
           source /mnt/petrelfs/qa-caif-cicd/env/ray1.13.0
           cd /mnt/petrelfs/qa-caif-cicd/tmp
      - name: slurm demo
        run: |
          sh ./slurm.sh
