name: demo test yaml

on: [push]

jobs:
  build:

    runs-on: ktest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      #- name: Set up Python ${{ matrix.python-version }}
        #uses: actions/setup-python@v4
        #with:
          #python-version: ${{ matrix.python-version }}
      - name: run demo python
        run: |
          source /mnt/petrelfs/qa-caif-cicd/env/ray1.13.0
          python ./demo.py
      - name: kk echo demo
        run: |
          # stop the build if there are Python syntax errors or undefined names
          echo $PATH
      - name: tmp
        run: |
           source /mnt/petrelfs/qa-caif-cicd/env/ray1.13.0
           pip show ray
      - name: slurm demo
        run: |
          sh ./slurm.sh
